### ISSUE TITLE
Cannot compile for BBC microbit

### ISSUE THREAD

**Issue by vapniks** [technoblogy/ulisp-arm#16]
Following these instructions: http://www.ulisp.com/show?2672#example_programs
I get the following error at line 1197 when I try to upload the ulisp-arm code to my BBC microbit: `'else' without a previous 'if'`
The error is in the definition of `serialbegin`, and I guess it is because `_VARIANT_BBC_MICROBIT_` is defined, and `ARDUINO_SAM_DUE` is not defined, so the precompiler skips over the previous `if` statements.

**Comment by technoblogy** [comment]
Sorry about the delay in replying - GitHub doesn't seem to be emailing me about issues posted to my repositories.

I'll investigate and get back to you.

**Comment by technoblogy** [comment]
Yes, just remove/comment out the line

    else error(WITHSERIAL, PSTR("port not supported"), number(address));

I'll fix it properly next release. Thanks for reporting it.
