### ISSUE TITLE
(lambda x x) loops forever

### ISSUE THREAD

**Issue by rmu75** [technoblogy/ulisp-arm#32]
I think a more sensible behaviour is possible. Either error or do like in scheme (bind x to the list of arguments):

```lisp
((lambda x x) 1 2 3))
=> (1 2 3)
```

**Comment by technoblogy** [comment]
Thanks! I think I should do what Common Lisp does and give an error.

**Comment by technoblogy** [comment]
By the way, uLisp can bind to the list of arguments using **&rest**:
````
> ((lambda (&rest x) x) 1 2 3)
(1 2 3)
````
