### ISSUE TITLE
Adafruit Feather M4 Express analog read range extension to 20 (A6)

### ISSUE THREAD

**Issue by sncsoft** [technoblogy/ulisp-arm#38]
Thank you for beautiful uLisp. Adafruit Feather M4 Express function analogread argument is limited from 14 (A0) to 19 (A5) ports. This range match external analog inputs for the board. But there is internal, not exposed A6 analog input which provides reading for battery voltage. This value is quite usable and it make sense to extend analogread function's range from 14 (A0) to 20 (A6).
SNC.

**Comment by technoblogy** [comment]
Thanks! I'll add that next release. David
